// apps/api/src/common/middleware/auth.middleware.ts

import { Request, Response, NextFunction } from 'express';
import jwt from 'jsonwebtoken';
import { AppError } from '../errors/AppError';
import { logger } from '../logging/logger';

/**
 * JWT Payload Structure
 * Matches token claims generated by auth.service
 */
export interface JwtPayload {
  userId: string;
  tenantId: string;
  roleId: string;
  username: string;
  roleName: string;
  permissions: string[];
}

// Extend Express Request for type safety
declare global {
  namespace Express {
    interface Request {
      tenantId?: string;
      user?: JwtPayload;
    }
  }
}

/**
 * Authentication Middleware (Layer 1 Security)
 *
 * PURPOSE:
 * - Extract Bearer token from Authorization header
 * - Cryptographically verify JWT signature
 * - Extract tenant_id and user claims
 * - Attach verified claims to request object
 * - REJECT any client-supplied tenant headers (X-Tenant-ID)
 *
 * CRITICAL RULE:
 * - Tenant identity MUST come ONLY from JWT claims
 * - Client headers like X-Tenant-ID are completely ignored
 * - This prevents tenant-hijacking vulnerabilities
 *
 * FLOW:
 * 1. Extract Bearer token from Authorization header
 * 2. Verify signature using JWT_ACCESS_SECRET
 * 3. Validate token claims have required fields
 * 4. Attach to req.tenantId and req.user for downstream use
 * 5. Next middleware (tenantTransactionMiddleware) stores in AsyncLocalStorage
 *
 * ============================================================================
 */

export const authMiddleware = (req: Request, res: Response, next: NextFunction): void => {
  try {
    // Step 1: Extract Authorization header
    const authHeader = req.headers.authorization;

    if (!authHeader) {
      throw new AppError(
        'Authentication failed: Missing Authorization header. Expected: Authorization: Bearer <token>',
        401
      );
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new AppError(
        'Authentication failed: Invalid Authorization header format. Expected: Authorization: Bearer <token>',
        401
      );
    }

    // Step 2: Extract token from "Bearer <token>" format
    const token = authHeader.substring(7); // Skip "Bearer "

    if (!token) {
      throw new AppError(
        'Authentication failed: Token is empty',
        401
      );
    }

    // Step 3: Get JWT secret from environment
    const secret = process.env.JWT_ACCESS_SECRET;
    if (!secret) {
      logger.error('CRITICAL CONFIGURATION ERROR: JWT_ACCESS_SECRET not set');
      throw new AppError(
        'Internal server error: JWT configuration missing',
        500
      );
    }

    // Step 4: Verify JWT signature and extract claims
    let decoded: JwtPayload;
    try {
      decoded = jwt.verify(token, secret) as JwtPayload;
    } catch (jwtError: any) {
      if (jwtError.name === 'TokenExpiredError') {
        throw new AppError(
          'Authentication failed: Token has expired',
          401
        );
      }
      if (jwtError.name === 'JsonWebTokenError') {
        throw new AppError(
          'Authentication failed: Invalid token signature',
          401
        );
      }
      throw new AppError(
        'Authentication failed: Token verification failed',
        401
      );
    }

    // Step 5: Validate token structure (claims integrity check)
    if (!decoded.tenantId || !decoded.userId || !decoded.roleId || !decoded.permissions) {
      throw new AppError(
        'Authentication failed: Token claims incomplete. Missing: tenantId, userId, roleId, or permissions',
        401
      );
    }

    // Step 6: Attach verified claims to request
    // CRITICAL: Ignore any client-supplied X-Tenant-ID header
    req.tenantId = decoded.tenantId;
    req.user = decoded;

    logger.debug('Authentication successful', {
      tenantId: decoded.tenantId,
      userId: decoded.userId,
      roleName: decoded.roleName,
      path: req.path,
    });

    // Step 7: Continue to next middleware
    next();
  } catch (error) {
    // Always log auth failures for security monitoring
    if (error instanceof AppError && error.statusCode === 401) {
      logger.warn('Authentication failed', {
        path: req.path,
        error: error.message,
      });
    } else {
      logger.error('Authentication error', {
        error: error instanceof Error ? error.message : String(error),
      });
    }
    next(error);
  }
};
