// File Path: apps/api/src/common/middleware/auth.middleware.ts

import { Request, Response, NextFunction } from 'express';
import jwt from 'jsonwebtoken';
import { AppError } from '../errors/AppError';
import { logger } from '../logging/logger';
import { tenantStorage } from '../tenant-context';

/**
 * Standardized structure matching token payloads generated by auth.service
 */
export interface JwtPayload {
  userId: string;
  tenantId: string;
  roleId: string;
  username: string;
  roleName: string;
  permissions: string[];
}

// Extend Express Request typing context to maintain absolute compile-time safety
declare global {
  namespace Express {
    interface Request {
      tenantId?: string;
      user?: JwtPayload;
    }
  }
}

/**
 * Layer 1 Context Enforcement Middleware
 * Unpacks the Authorization Bearer token, cryptographically validates the signature,
 * extracts tenant_id metadata, and binds it to AsyncLocalStorage request thread context.
 * Explicitly ignores untrusted client headers to neutralize tenant-tampering exploits.
 */
export const authenticateTenant = (req: Request, res: Response, next: NextFunction): void => {
  try {
    const authHeader = req.headers.authorization;
    
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      throw new AppError('Authentication failed: Missing or malformed Bearer authorization vector', 401);
    }

    const token = authHeader.split(' ')[1];
    if (!token) {
      throw new AppError('Authentication failed: Token signature vector is empty', 401);
    }

    const secret = process.env.JWT_ACCESS_SECRET;
    if (!secret) {
      logger.error('CRITICAL CONFIGURATION ERROR: JWT_ACCESS_SECRET is undefined within the environment vectors.');
      throw new AppError('Internal server orchestration fault', 500);
    }

    let decoded: JwtPayload;
    try {
      decoded = jwt.verify(token, secret) as JwtPayload;
    } catch (jwtError: any) {
      if (jwtError.name === 'TokenExpiredError') {
        throw new AppError('Authentication failed: Provided security token has expired', 401);
      }
      throw new AppError('Authentication failed: Cryptographic token signature is invalid', 401);
    }

    if (!decoded.tenantId || !decoded.userId || !decoded.permissions) {
      throw new AppError('Authentication failed: Token claims fail structural integrity checks', 401);
    }

    // Neutralize tampering vulnerabilities by binding validated claims directly to the internal request
    req.tenantId = decoded.tenantId;
    req.user = decoded;

    // Execute the remaining execution branch context within isolated multi-tenant async stores
    tenantStorage.run(
      { 
        tenantId: decoded.tenantId, 
        userId: decoded.userId, 
        roleId: decoded.roleId 
      }, 
      () => {
        next();
      }
    );
  } catch (error) {
    next(error);
  }
};

/**
 * RBAC Role Permission Verification Factory
 * Cross-references the tenant context's authenticated permissions claim array against
 * required capability mappings before granting downstream execution paths.
 */
export const requirePermission = (requiredPermission: string) => {
  return (req: Request, res: Response, next: NextFunction): void => {
    if (!req.user || !req.user.permissions) {
      return next(new AppError('Access denied: Unauthorized identity domain context', 403));
    }

    const hasPermission = req.user.permissions.includes(requiredPermission);
    if (!hasPermission) {
      logger.warn(
        `Security Authorization Violation Attempt: User [${req.user.userId}] on Tenant [${req.tenantId}] rejected from resource path requiring permission [${requiredPermission}]`
      );
      return next(
        new AppError(`Access denied: Core authority role mismatch. Missing permission capability: [${requiredPermission}]`, 403)
      );
    }

    next();
  };
}; 