import { db } from '../../config/database';
import { v4 as uuidv4 } from 'uuid';

export class AutomationEngine {

  /**
   * Main entry point for triggering automations.
   * Runs asynchronously so it doesn't block the main API response.
   */
  static async processEvent(tenantId: string, eventType: string, contextData: any) {
    try {
      // 1. Fetch all ACTIVE rules for this specific event type and tenant
      const rules = await db('automation_rules')
        .where({ tenant_id: tenantId, trigger_event: eventType, is_active: true });

      if (rules.length === 0) return; // No rules configured for this event

      for (const rule of rules) {
        // 2. Fetch Conditions and Actions for the rule
        const conditions = await db('automation_conditions').where({ rule_id: rule.rule_id });
        const actions = await db('automation_actions').where({ rule_id: rule.rule_id });

        // 3. Evaluate Conditions
        const conditionsMet = this.evaluateConditions(conditions, contextData);

        if (conditionsMet) {
          // 4. Create an Execution Run Log (Audit Trail - Phase 5 Requirement)
          const runId = uuidv4();
          await db('automation_execution_runs').insert({
            run_id: runId,
            tenant_id: tenantId,
            rule_id: rule.rule_id,
            status: 'PROCESSING',
            executed_at: new Date().toISOString()
          });

          // 5. Execute Actions
          try {
            await this.executeActions(tenantId, actions, contextData);

            // Mark Run Success
            await db('automation_execution_runs')
              .where({ run_id: runId })
              .update({ status: 'SUCCESS' });

          } catch (actionError: any) {
            // Mark Run Failed but DO NOT crash the engine
            await db('automation_execution_runs')
              .where({ run_id: runId })
              .update({
                status: 'FAILED',
                logs: actionError.message
              });
          }
        }
      }
    } catch (error) {
      console.error('[Automation Engine Critical Failure]:', error);
    }
  }

  /**
   * Compares the live event data against the database conditions
   */
  private static evaluateConditions(conditions: any[], contextData: any): boolean {
    // If ANY condition fails, the whole rule fails (AND logic)
    for (const cond of conditions) {
      const liveValue = contextData[cond.field];
      const ruleValue = Number(cond.value) || cond.value; // Coerce types if needed

      switch (cond.operator) {
        case 'EQUALS':
          if (liveValue !== ruleValue) return false;
          break;
        case 'GREATER_THAN':
          if (liveValue <= ruleValue) return false;
          break;
        case 'LESS_THAN':
          if (liveValue >= ruleValue) return false;
          break;
        default:
          return false;
      }
    }
    return true; // All conditions passed
  }

  /**
   * Executes the mapped actions based on their type
   */
  private static async executeActions(tenantId: string, actions: any[], contextData: any) {
    for (const action of actions) {
      const config = typeof action.configuration === 'string'
        ? JSON.parse(action.configuration)
        : action.configuration;

      switch (action.action_type) {

        case 'LOCK_TILL':
          if (!contextData.till_session_id) throw new Error('Missing till_session_id for LOCK_TILL');

          await db('till_sessions')
            .where({ till_session_id: contextData.till_session_id, tenant_id: tenantId })
            .update({ status: 'LOCKED' });

          await this.logSystemAudit(tenantId, 'TILL_LOCKED_BY_AUTOMATION', contextData.till_session_id);
          break;

        case 'AUTO_ORDER':
          if (!contextData.product_id || !contextData.supplier_id) {
            throw new Error('Missing product context for AUTO_ORDER');
          }

          await db('purchase_orders').insert({
            po_id: uuidv4(),
            tenant_id: tenantId,
            supplier_id: contextData.supplier_id,
            status: 'DRAFT_AUTOMATED',
            total_amount: 0.00,
            notes: `Auto-generated by Rule Configuration: ${config.reorder_reason || 'Low Stock'}`
          });
          break;

        case 'ALERT_OWNER':
          await db('notification_outbox').insert({
            id: uuidv4(),
            tenant_id: tenantId,
            message: config.message_template.replace('{{product}}', contextData.product_name),
            status: 'PENDING',
            priority: 'HIGH'
          });
          break;

        default:
          console.warn(`[Automation Engine] Unknown action type: ${action.action_type}`);
      }
    }
  }

  // Helper for strict auditing (Rule #4: Never delete audit history)
  private static async logSystemAudit(tenantId: string, action: string, entityId: string) {
    await db('audit_logs').insert({
      audit_log_id: uuidv4(),
      tenant_id: tenantId,
      action: action,
      entity_name: 'AUTOMATION_SYSTEM',
      entity_id: entityId,
      client_ip: 'system-internal'
    });
  }
}